/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import proj.vo.CouponListPanelVO;
import proj.vo.CouponVO;

/**
 *
 * @author minhopark
 */
public class CouponList extends javax.swing.JFrame {
    Coupon_Login f;
    Main mainform;
    ButtonGroup bg;
    ArrayList<CouponListPanelVO> cpvo_list;
    
    /**
     * Creates new form CouponList
     */
    public CouponList(Coupon_Login f, Main mainform) {
        this.f = f;
        this.mainform = mainform;
        
        bg = new ButtonGroup();
        cpvo_list = new ArrayList<>();
        
        initComponents();
        setUI();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        p_Coupon = new javax.swing.JPanel();
        btnUseCoupon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        p_Coupon.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(p_Coupon);

        btnUseCoupon.setText("선택 쿠폰 사용");
        btnUseCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUseCouponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUseCoupon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnUseCoupon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 쿠폰 사용하기 버튼
    private void btnUseCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUseCouponActionPerformed
        // 라디오버튼 텍스트 가져오기
        Enumeration<AbstractButton> tmp = bg.getElements();
        String s = null;
        while (tmp.hasMoreElements()){
            AbstractButton ab = tmp.nextElement();
            JRadioButton jb = (JRadioButton)ab;
            if (jb.isSelected())
                s = jb.getText();
        }
        
        // 선택한 쿠폰 정보 가져온 후 mainform 변수 세팅
        for (int i = 0; i < cpvo_list.size(); i++){
            CouponListPanelVO cpvo = cpvo_list.get(i);
            if (cpvo.cp_vo.getCoupon_name().equals(s)){
                mainform.coupon_index = cpvo.cp_vo.getCoupon_idx();
                mainform.discountPrice = cpvo.cp_vo.getDiscount();
                mainform.setPrice();
                mainform.isCoupon = 1;
                mainform.user_index = f.u_idx;
                break;
            }
        }
        
        dispose();
    }//GEN-LAST:event_btnUseCouponActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CouponList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CouponList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CouponList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CouponList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // 쿠폰 리스트 화면 구성
    private void setUI() {
        for(int i =0; i< f.coupon_list.size(); i++) {
            CouponVO cvo = f.coupon_list.get(i).cvo;
            CouponListPanelVO cpvo = new CouponListPanelVO(cvo);
            cpvo_list.add(cpvo);
            bg.add(cpvo.jrb);
            p_Coupon.add(cpvo.jrb);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUseCoupon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_Coupon;
    // End of variables declaration//GEN-END:variables
}