/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proj;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import org.apache.ibatis.session.SqlSession;
import proj.vo.MenuVO;
import proj.vo.StockVO;

/**
 *
 * @author 2015k
 */
public class MenuDialog extends javax.swing.JDialog {

    /**
     * Creates new form MenuJDialog
     */
    Main f;
    int type;
    String m_idx;
    
    
    public MenuDialog(String type, Main f) {
        this.f = f;
        this.type = 0; // 추가
        initComponents();
        delete_btn.setVisible(false);
        m_add_stock_tf.setEditable(false);
        switch(f.clDrinksCard){
            case "cardCoffeeAdmin":
                m_cate_cb.setSelectedIndex(0);
                break;
            case "cardNonCoffeeAdmin":
                m_cate_cb.setSelectedIndex(1);
                break;
            case "cardAdeAdmin":
                m_cate_cb.setSelectedIndex(2);
                break;
        }
        m_cate_cb.setEnabled(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    public MenuDialog(String type, MenuVO m_vo, Main f) {
        this.f = f;
        this.type = 1; // 수정
        m_idx = m_vo.getM_idx();
        initComponents();
        title.setText("메뉴 수정");
        delete_btn.setVisible(true);
        m_name_tf.setText(m_vo.getM_name());
        m_cate_cb.setSelectedIndex(Integer.parseInt(m_vo.getCategory_idx())-1);
        m_price_tf.setText(m_vo.getPrice());
        unit_price_tf.setText(m_vo.getUnit_price());
        m_time_tf.setText(m_vo.getBrew_time());
        m_stock_tf.setText(m_vo.getStock());
        m_stock_tf.setEditable(false);
        m_imgUrl_tf.setText(m_vo.getImg_url());
        m_desc_tf.setText(m_vo.getDesc());
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public MenuDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        m_name_tf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        m_price_tf = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        unit_price_tf = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        m_time_tf = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        m_stock_tf = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        m_add_stock_tf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        addUpt_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        m_cate_cb = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        m_imgUrl_tf = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        m_desc_tf = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        title = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel1.setText("메뉴명 :");

        m_name_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_name_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_name_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(m_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel3.setText("가격 :");

        m_price_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_price_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_price_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_price_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, 50));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel7.setText("단가 :");

        unit_price_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        unit_price_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        unit_price_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit_price_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit_price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel4.setText("조리시간 :");

        m_time_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_time_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_time_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_time_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_time_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_time_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 240, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel5.setText("재고 :");

        m_stock_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_stock_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_stock_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_stock_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_stock_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_stock_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 240, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel6.setText("추가재고 :");

        m_add_stock_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_add_stock_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_add_stock_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_add_stock_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_add_stock_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_add_stock_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addUpt_btn.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        addUpt_btn.setText("저장");
        addUpt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpt_btnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jButton4.setText("닫기");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(addUpt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUpt_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 240, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel9.setText("분류 :");

        m_cate_cb.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        m_cate_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "커피", "논커피", "에이드" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(m_cate_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(m_cate_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel10.setText("이미지Url :");

        m_imgUrl_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_imgUrl_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_imgUrl_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_imgUrl_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_imgUrl_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_imgUrl_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 240, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        jLabel11.setText("설명 :");

        m_desc_tf.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        m_desc_tf.setPreferredSize(new java.awt.Dimension(80, 28));
        m_desc_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_desc_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_desc_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_desc_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 240, -1));

        delete_btn.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        delete_btn.setText("삭제");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 85, 30));

        title.setEditable(false);
        title.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        title.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title.setText("메뉴추가");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_add_stock_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_add_stock_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_add_stock_tfActionPerformed

    private void m_stock_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_stock_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_stock_tfActionPerformed

    private void m_time_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_time_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_time_tfActionPerformed

    private void m_price_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_price_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_price_tfActionPerformed

    private void m_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_name_tfActionPerformed

    private void m_imgUrl_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_imgUrl_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_imgUrl_tfActionPerformed

    private void m_desc_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_desc_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_desc_tfActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        
        int res = JOptionPane.showConfirmDialog(this, "정말 삭제하시겠습니까?");
        if (res == JOptionPane.YES_OPTION){
          if(f.delete_menu(m_idx) == 1){
            JOptionPane.showMessageDialog(this, "해당 메뉴가 삭제되었습니다.");
            }  
        }
        
        this.dispose();
        
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addUpt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpt_btnActionPerformed
        // TODO add your handling code here:
        
        Map<String, String> menu_map = new HashMap<>();
        
        
        menu_map.put("m_idx",m_idx);
        
        // 이름
        String m_name = m_name_tf.getText().trim();
        if(m_name.length()==0){
            JOptionPane.showMessageDialog(f,"메뉴명을 입력해주세요.");
            return;
        }
        menu_map.put("m_name",m_name);
        
        //카테고리
        String category_idx = String.valueOf(m_cate_cb.getSelectedIndex()+1);
        menu_map.put("category_idx",category_idx);
        
        //가격
        String price = m_price_tf.getText().trim();
        if(price.length()==0){
            JOptionPane.showMessageDialog(f,"가격을 입력해주세요.");
            return;
        }
        menu_map.put("price",price);
        
        //단가
        String unit_price = unit_price_tf.getText().trim();
        if(unit_price.length()==0){
            JOptionPane.showMessageDialog(f,"단가를 입력해주세요.");
            return;
        }
        menu_map.put("unit_price",unit_price);
        
        //시간
        String brew_time = m_time_tf.getText().trim();
        if(brew_time.length()==0){
            JOptionPane.showMessageDialog(f,"조리시간을 입력해주세요.");
            return;
        }
        menu_map.put("brew_time",brew_time);
        
        //이미지
        String img_url = m_imgUrl_tf.getText().trim();
        if (img_url.length() < 13 || !img_url.substring(0, 12).equals("/images/menu/"))
            menu_map.put("img_url", "/images/menu/noimg.png");
        else
            menu_map.put("img_url",img_url);
        
        //설명
        String desc = m_desc_tf.getText().trim();
        menu_map.put("desc",desc);
        
        //재고
        String stock = (m_stock_tf.getText().trim());
        if(stock.length() ==0){
            stock = "0";
        }
        
        switch(type){
            case 0: 
                    menu_map.put("stock",String.valueOf(stock));
                    if(f.add_menu(menu_map) == 1){
                        JOptionPane.showMessageDialog(this, "해당 메뉴가 추가되었습니다.");
                        f.startProgram();
                        this.dispose();
                    }
                break;
            case 1:
                    String addStock = m_add_stock_tf.getText().trim();
                    if(addStock.length() == 0){
                        menu_map.put("stock",String.valueOf(stock));
                    } else {
                        stockAdd(addStock);
                        
                        int stocks = Integer.parseInt(addStock)+Integer.parseInt(stock);
                        menu_map.put("stock",String.valueOf(stocks));
                    }
                    
                    if(f.update_menu(menu_map) == 1){
                        JOptionPane.showMessageDialog(this, "해당 메뉴가 수정되었습니다.");
                        this.dispose();
                    }
                break;
        }
        
        

    }//GEN-LAST:event_addUpt_btnActionPerformed

    private void unit_price_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unit_price_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unit_price_tfActionPerformed
    public void stockAdd(String add_stock){
        SqlSession ss = Main.factory.openSession();
                        
        Map<String, String> stock_map = new HashMap<>();
        stock_map.put("m_idx", m_idx);
        stock_map.put("add_stock", add_stock);
        stock_map.put("crt_dtm",ss.selectOne("stock.last_crtDtm",m_idx));
        
        
        int res = ss.insert("stock.update", stock_map);
        if(res == 1){
            ss.commit();
            System.out.println("재고관리 수정 완료.");
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuDialog dialog = new MenuDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUpt_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField m_add_stock_tf;
    private javax.swing.JComboBox<String> m_cate_cb;
    private javax.swing.JTextField m_desc_tf;
    private javax.swing.JTextField m_imgUrl_tf;
    private javax.swing.JTextField m_name_tf;
    private javax.swing.JTextField m_price_tf;
    private javax.swing.JTextField m_stock_tf;
    private javax.swing.JTextField m_time_tf;
    private javax.swing.JTextField title;
    private javax.swing.JTextField unit_price_tf;
    // End of variables declaration//GEN-END:variables
}
